config/routes.rb
Rails.application.routes.draw do   devise_for :users
  resources :shopping_list, only: %i[index]
  resources :foods
  resources :recipe_foods, only: %i[create destroy]
  resources :recipes
  resources :users
  resources :public_recipes
  resources :shopping_list

  #root to users#index acceced as public_recipes
  
  root to: 'public_recipes#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, -> { includes(:food) }, dependent: :destroy
  has_many :foods, through: :recipe_foods

  validates :name, presence: true
  validates :description, presence: true
  validates :preparation_time, presence: true
  validates :cooking_time, presence: true

  def public?
    public == true
  end

  def total_price
    recipe_foods.sum { |recipe_food| recipe_food.quantity * recipe_food.food.price }
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.where(user_id: current_user.id)
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @ingredients = RecipeFood.includes(:food).where(recipe_id: @recipe.id)
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit; end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully updated. Here ok' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public, :user_id_id)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :preparation_time, style: "display: block" %>
    <%= form.text_field :preparation_time %>
  </div>

  <div>
    <%= form.label :cooking_time, style: "display: block" %>
    <%= form.text_field :cooking_time %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :public, style: "display: block" %>
    <%= form.check_box :public %>
  </div>

  
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div class="d-flex justify-content-center flex-column">
    <h1 class="text-center mt-3 mb-5"><%= @recipe.name%></h1>
    <div id="recipe-details" class="flex">
      <div class="d-flex justify-content-between my-3">
        <div>
          <h3>
            Preparation time: <%=@recipe.preparation_time %>
          </h3>
          <h3>
            Cooking time: <%=@recipe.cooking_time %>
          </h3>
          </h3>
        </div>
        <div>
          <!-- ruby on rails checkbox activate or deactivate public mode -->

      

          <%= form_with model: @recipe do |form| %>
            <div class="form-check form-switch">
              <label class="form-check-label">Public</label>
              <%= form.check_box :public, {onchange: "this.form.requestSubmit();", class: "form-check-input", role: "switch"}%>
            </div>
          <% end %>

        </div>
      </div>
      <div class="description my-5">
        <p><%= @recipe.description %></p>
      </div>
    </div>

    <div id="form-buttons">
      <div class="d-flex justify-content-between">
        <%= link_to "Generate shopping list", shopping_list_index_path, class: "btn btn-primary" %>
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addIngredientModal">
          Add Ingredient
        </button>
      </div>
      <div class="separator"></div>
    </div>
        <!--%= render @ingredients[0] %-->
        
    <table class="table table-striped" id="ingredients">
      <thead>
        <tr>
          <th scope="col">Food</th>
          <th scope="col">Quantity</th>
          <th scope="col">Value</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
      <% @ingredients.each do |recipe_food| %>
        <%= render recipe_food %>
      <% end %>
      </tbody>
    </table>
</div>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<p style="color: green"><%= notice %></p>
<%= link_to "New recipe", new_recipe_path %>

<h1 class="text-center">Recipes</h1>

<div id="recipes">
  <% @recipes.each do |recipe| %>

    <div class="card p-3">
      
      <div class="d-flex justify-content-between"> 
        <div class="container">
          <p>
            <h3 >
              <%= link_to recipe.name, recipe_path(recipe.id) , class:"no-text-decoration" %>
            </h3>
          </p>
          <% if can? :destroy, recipe %>
            <%= link_to "Remove", recipe, 'data-turbo-method': :delete %>
          <%end%>
        </div>  

        <div class="col-6">
          <p>
            <%= recipe.description %>
          </p>
        </div>

      </div> 
    </div>  

  <% end %>
</div>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="modal fade" id="addIngredientModal" tabindex="-1" aria-labelledby="addFoodModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addFoodModalLabel">Add ingredient</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <h5>Select ingredient</h5>

        <%= form_with model: RecipeFood.new, url: recipe_foods_path, local: true do |form| %>
          <div class="mb-3">
            <%= form.collection_select :food_id, current_user.foods, :id, :name, { prompt: "-- Select food --" }, { class: "form-select", id: "food-selector" } %>
          </div>

          <div class="mb-3">
            <%= form.label :quantity %>
            <%= form.number_field :quantity, class: "form-control" %>
          </div>

          <%= form.hidden_field :recipe_id, value: @recipe.id %>
          
          <div class="mb-3">
            <%= form.submit "Add ingredient", class: "btn btn-primary" %>
          </div>
        <% end %>

      </div>
    </div>
  </div>
</div>

<div>
  <!--%= link_to "Edit this recipe", edit_recipe_path(@recipe) %-->
  <%= link_to "Back to recipes", recipes_path %>

  <!--%= button_to "Destroy this recipe", @recipe, method: :delete %-->
</div>
<%= render @recipe %>